-- AlterTable
ALTER TABLE "SessionExercise" ADD COLUMN     "maxWeight" DOUBLE PRECISION,
ADD COLUMN     "setsCompleted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "setsSkipped" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalVolume" DOUBLE PRECISION;
